chore: improve score corruption error message
TimefoldAI/timefold-solver-benchmarks pull request #14
Opened 2024-05-02 09:52 UTC by triceo

2024-05-02 15:13 UTC, Christopher-Chianelli approved these changes

2024-05-02 15:14 UTC, Christopher-Chianelli requested changes
Test failing; cannot infer type of a variable in a test.

2024-05-02 15:15 UTC, Christopher-Chianelli commented
```
timefold-solver-benchmarks/src/main/java/ai/timefold/solver/benchmarks/micro/scoredirector/problems/AbstractProblem.java:[111,22] cannot infer type arguments for ai.timefold.solver.core.impl.localsearch.scope.LocalSearchPhaseScope<>
  reason: cannot infer type-variable(s) Solution_
    (actual and formal argument lists differ in length)
```

2024-05-03 05:41 UTC, triceo commented
The problem comes from the CI, not from the build. (CI checks out the wrong branch.)
Merging.

2024-05-03 05:41 UTC, merged